### ISSUE TITLE
 Cannot find module 'p-memoize'

### ISSUE THREAD

**Issue by hisham** [sindresorhus/p-memoize#42]
I'm importing pMemoize in a typescript project as follows: 

`import pMemoize from 'p-memoize';`

But I get error: 'Cannot find module 'p-memoize'. 

I do have p-memoize in package.json and am running typescript 4.5

**Comment by jlecomte** [comment]
Until the author adds the [`"main"` field](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#main) to its `package.json`, you can change your code to:

```js
import pMemoize from 'p-memoize/dist/index';
```

Hope this helps! Fixing the package itself should be easy so I hope the maintainer does it, primarily because the docs are out of sync with reality. Thanks in advance!

**Comment by hisham** [comment]
I tried that but got an error related to mimic-fn. I'm not on computer now though and I moved on to another lib.

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
